FROM python:3.7

WORKDIR /usr/src/app
COPY ./backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY ./backend/app ./app
COPY ./Version ../
ENV TPMJ_BACKEND_PRODUCTION 1
CMD [ "python", "app/main.py" ]
