name: bump version

on:
  push:
    branches:
      - master

jobs:
  my_job:
    name: bump version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Let git know who I am.
      run: |
        git config --global user.name "zjma"
        git config --global user.email "meshiadia@gmail.com"
    - name: Update ./Version
      run: |
        OldVersion=`cat Version`
        major=`cat Version | awk -F. '{print $1}'`
        minor=`cat Version | awk -F. '{print $2}'`
        patch=`cat Version | awk -F. '{print $3}'`
        let minor=minor+1
        NewVersion=$major.$minor.$patch
        echo NewVersion=$NewVersion
        echo $NewVersion > Version
        git add .
        git commit -m "Bump version from $OldVersion to $NewVersion."
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
